# Generated by Django 5.0.1 on 2024-02-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('id_autor', models.IntegerField()),
                ('writing_year', models.IntegerField()),
                ('id_publisher', models.IntegerField()),
                ('id_genre', models.IntegerField()),
                ('description', models.TextField()),
                ('book_image', models.ImageField(upload_to='book-photos/%Y')),
                ('fb2_path', models.FilePathField()),
                ('epub_path', models.FilePathField()),
                ('mp3_path', models.FilePathField()),
                ('book_feedback', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
