# Generated by Django 5.0.1 on 2024-03-04 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_author', models.CharField(max_length=50, verbose_name='ФИО автора')),
                ('biography', models.TextField(max_length=2100, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='authors/avatar', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['fio_author'],
            },
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_series', models.CharField(max_length=35, verbose_name='Название цикла')),
            ],
            options={
                'verbose_name': 'Цикл книг',
                'verbose_name_plural': 'Циклы книг',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=50, verbose_name='Названия издательства')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.CreateModel(
            name='TypeOfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_book', models.CharField(max_length=50, verbose_name='Тип книги')),
            ],
            options={
                'verbose_name': 'Тип книги',
                'verbose_name_plural': 'Тип книг',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('book_ind', models.SmallIntegerField(default=0, verbose_name='Номер в цикле')),
                ('writing_year', models.IntegerField(verbose_name='Год написания')),
                ('description', models.TextField(max_length=1250, verbose_name='Описание')),
                ('read_text', models.TextField(verbose_name='Содержание книги')),
                ('book_image', models.ImageField(upload_to='books/%Y/%mv0e4k0z1h8m0', verbose_name='Обложка книги')),
                ('fb2_path', models.FileField(upload_to='books/%Y/%mv0e4k0z1h8m0', verbose_name='fb2 файл')),
                ('epub_path', models.FileField(blank=True, upload_to='books/%Y/%mv0e4k0z1h8m0', verbose_name='epub файл')),
                ('mp3_path', models.FileField(blank=True, upload_to='books/%Y/%mv0e4k0z1h8m0', verbose_name='mp3 файл')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.author', verbose_name='Автор')),
                ('book_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_storage.bookseries', verbose_name='Цикл')),
                ('id_genre', models.ManyToManyField(to='book_storage.genre', verbose_name='Жанры')),
                ('id_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.publisher', verbose_name='Издатель')),
                ('type_of_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.typeofbook', verbose_name='Тип книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['time_update', 'title'],
            },
        ),
    ]
