# Generated by Django 5.0.1 on 2024-03-09 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='book_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_storage.bookseries', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.book'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='id_genre',
            field=models.ManyToManyField(to='book_storage.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='likedbook',
            name='liked_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.book'),
        ),
        migrations.AddField(
            model_name='likedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='id_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.publisher', verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='book',
            name='type_of_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.typeofbook', verbose_name='Тип книги'),
        ),
    ]
