# Generated by Django 5.0.1 on 2024-02-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_autor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_feedback',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.publisher'),
        ),
    ]
