# Generated by Django 5.0.1 on 2024-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_verified',
            field=models.BooleanField(choices=[(False, 'Не проверено'), (True, 'Проверено')], default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%md0n0v6t8h4u9', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%md0n0v6t8h4u9', verbose_name='epub файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%md0n0v6t8h4u9', verbose_name='fb2 файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%md0n0v6t8h4u9', verbose_name='mp3 файл'),
        ),
    ]
