# Generated by Django 5.0.1 on 2024-02-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0002_autor_genre_publisher_remove_book_book_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
