# Generated by Django 5.0.1 on 2024-02-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0003_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writing_year', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('book_image', models.ImageField(upload_to='book-photos/%Y')),
                ('fb2_path', models.FilePathField(blank=True)),
                ('epub_path', models.FilePathField(blank=True)),
                ('mp3_path', models.FilePathField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.autor')),
                ('id_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.genre')),
                ('id_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.publisher')),
            ],
        ),
    ]
