# Generated by Django 5.0.1 on 2024-02-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FilePathField(blank=True, path='book_epub/%Y'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FilePathField(blank=True, path='book_fb2/%Y'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FilePathField(blank=True, path='book_mp3/%Y'),
        ),
    ]
