# Generated by Django 5.0.1 on 2024-02-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0005_alter_book_epub_path_alter_book_fb2_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/<django.db.models.fields.charfield>'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(upload_to='books/%Y/<django.db.models.fields.charfield>'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/<django.db.models.fields.charfield>'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(upload_to='books/%Y/<django.db.models.fields.charfield>'),
        ),
    ]
