# Generated by Django 5.0.1 on 2024-02-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0006_alter_book_book_image_alter_book_epub_path_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='fio_autor',
            new_name='fio_author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id_autor',
            new_name='id_author',
        ),
    ]
