# Generated by Django 5.0.1 on 2024-02-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0007_rename_autor_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%M<function Book.Helper.create_file_path at 0x0000002119C41260>'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(upload_to='books/%Y/%M<function Book.Helper.create_file_path at 0x0000002119C41260>'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%M<function Book.Helper.create_file_path at 0x0000002119C41260>'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(upload_to='books/%Y/%M<function Book.Helper.create_file_path at 0x0000002119C41260>'),
        ),
    ]
