# Generated by Django 5.0.1 on 2024-02-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0010_alter_book_book_image_alter_book_epub_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_book', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%mr5z5e0y5c5m0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mr5z5e0y5c5m0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%mr5z5e0y5c5m0'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mr5z5e0y5c5m0'),
        ),
        migrations.AddField(
            model_name='book',
            name='id_genre',
            field=models.ManyToManyField(to='book_storage.genre'),
        ),
    ]
