# Generated by Django 5.0.1 on 2024-02-09 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0011_typeofbook_alter_book_book_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type_of_book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='book_storage.typeofbook'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%mo1t3v8m7y1o0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mo1t3v8m7y1o0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%mo1t3v8m7y1o0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mo1t3v8m7y1o0'),
        ),
    ]
