# Generated by Django 5.0.1 on 2024-02-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0012_book_type_of_book_alter_book_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%mx8c2h6t1g4b6'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mx8c2h6t1g4b6'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%mx8c2h6t1g4b6'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mx8c2h6t1g4b6'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type_of_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.typeofbook'),
        ),
    ]
