# Generated by Django 5.0.1 on 2024-03-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0014_author_biography_author_photo_alter_book_book_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['fio_author'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['time_update', 'title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
        migrations.AlterModelOptions(
            name='typeofbook',
            options={'verbose_name': 'Тип книги', 'verbose_name_plural': 'Тип книг'},
        ),
        migrations.AddField(
            model_name='book',
            name='book_series',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='book',
            name='read_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(max_length=2100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%mr4o8b7z1q9d9'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mr4o8b7z1q9d9'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%mr4o8b7z1q9d9'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mr4o8b7z1q9d9'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
