# Generated by Django 5.0.1 on 2024-03-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0019_alter_book_book_image_alter_book_book_series_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookseries',
            options={'verbose_name': 'Цикл книг', 'verbose_name_plural': 'Циклы книг'},
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(max_length=2100, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='author',
            name='fio_author',
            field=models.CharField(max_length=50, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to='authors/avatar', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%mg0z7a1j4t8o3', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_storage.bookseries', verbose_name='Цикл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mg0z7a1j4t8o3', verbose_name='epub файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%mg0z7a1j4t8o3', verbose_name='fb2 файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id_genre',
            field=models.ManyToManyField(to='book_storage.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.publisher', verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%mg0z7a1j4t8o3', verbose_name='mp3 файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_text',
            field=models.TextField(verbose_name='Содержание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type_of_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.typeofbook', verbose_name='Тип книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='writing_year',
            field=models.IntegerField(verbose_name='Год написания'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='book_series',
            field=models.CharField(max_length=35, verbose_name='Название цикла'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name',
            field=models.CharField(max_length=50, verbose_name='Названия издательства'),
        ),
        migrations.AlterField(
            model_name='typeofbook',
            name='type_of_book',
            field=models.CharField(max_length=50, verbose_name='Тип книги'),
        ),
    ]
