# Generated by Django 5.0.1 on 2024-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0020_alter_bookseries_options_alter_author_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%ml5c0l9v0w5c2', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%ml5c0l9v0w5c2', verbose_name='epub файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%ml5c0l9v0w5c2', verbose_name='fb2 файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%ml5c0l9v0w5c2', verbose_name='mp3 файл'),
        ),
    ]
