# Generated by Django 5.0.1 on 2024-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0021_alter_book_book_image_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseries',
            name='book_ind',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Номер книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%ma0a2b7n8v5a6', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%ma0a2b7n8v5a6', verbose_name='epub файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%ma0a2b7n8v5a6', verbose_name='fb2 файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%ma0a2b7n8v5a6', verbose_name='mp3 файл'),
        ),
    ]
