# Generated by Django 5.0.1 on 2024-03-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0022_bookseries_book_ind_alter_book_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseries',
            name='book_ind',
        ),
        migrations.AddField(
            model_name='book',
            name='book_ind',
            field=models.SmallIntegerField(default=0, verbose_name='Номер книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/%Y/%ms6r7w4g2c2p8', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%ms6r7w4g2c2p8', verbose_name='epub файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_path',
            field=models.FileField(upload_to='books/%Y/%ms6r7w4g2c2p8', verbose_name='fb2 файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_path',
            field=models.FileField(blank=True, upload_to='books/%Y/%ms6r7w4g2c2p8', verbose_name='mp3 файл'),
        ),
    ]
