# Generated by Django 5.0.1 on 2024-03-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='user6754568900', max_length=15, verbose_name='Отображаемое имя'),
        ),
    ]
