# Generated by Django 5.0.1 on 2024-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='user6068148779', max_length=15, verbose_name='Отображаемое имя'),
        ),
    ]
