# Generated by Django 5.0.1 on 2024-03-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='user5961964645', max_length=15, verbose_name='Отображаемое имя'),
        ),
    ]
